### ISSUE TITLE
Message d'erreur

### ISSUE THREAD

**Issue by gpensta** [Eywek/tgvmax-bot#11]
Bonjour, 

J'ai construit l'image avec la dernière version. 
Je ne vois pas où modifier la configuration nginx donc je n'ai rien touché. 

Quand je lance le conteneur front et le back et que je veux ajouter un trajet, j'ai le message d'erreur suivant  coté front : 

```
2022/04/25 16:50:13 [error] 37#37: *6 open() "/usr/share/nginx/html/api/stations/autocomplete" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /api/stations/autocomplete?searchTerm=Paris HTTP/1.1", host: "localhost:8081", referrer: "http://localhost:8081/"
```

Je n'y connais pas grand chose, merci d'avance pour votre aide.

**Comment by MrVidipy** [comment]
Bonjour @Eywek , 

J'ai le même problème que @gpensta .

Sachant que j'ai aussi une erreur à l'ouverture d'une page du frontend : 
`2022/09/17 14:46:53 [error] 24#24: *1 open() "/usr/share/nginx/html/api/travels" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /api/travels HTTP/1.1", host: "localhost:8081", referrer: "http://localhost:8081/"`

Merci d'avance.

**Comment by MrVidipy** [comment]
Problème résolu,
Au final le problème était que j'utilisais 127.0.0.1:8081 au lieu de 192.168.0.13:8081;
Explication [ici](https://stackoverflow.com/a/47663730)
