### ISSUE TITLE
Cannot run docker command for backend

### ISSUE THREAD

**Issue by remmmmmm** [Eywek/tgvmax-bot#12]
Hey ! First of all, thanks for your work, it is very rare to find TGV max bots with the new SNCF API.

The frontend works perfectly but I have an issue when I try to run the backend.

Here is the logs : 

```
The path /home/eywek/docker/tgvmax/tgvmax.sqlite is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
```

Is `tgvmax.sqlite` shared somewhere ? Am I doing something wrong ?

Thanks in advance,
Rémi

**Comment by Eywek** [comment]
Hello

You can create an empty file named tgvmax.sqlite and the backend should populate the db itself
