### ISSUE TITLE
Better to add authentication to the front-end application

### ISSUE THREAD

**Issue by Akanichi** [Eywek/tgvmax-bot#23]
As the front end is accessible to everyone on the web, i think it's better to add a username and password for the authentication on the front-end.

**Comment by germainroussez** [comment]
The idea behind this issue would be to deploy the two containers on a remote server (VPS on OVH for example) and run the frontend on public IP. We'd then be able to access to the bot from any device with username/password and the bot would be able to run H24.

**Comment by Eywek** [comment]
It would add complexity that isn't needed IMHO. 

If you want authentification you can configure your reverse proxy (i.e. NGinx) to use basic authentification
